# Generated by Django 3.0.3 on 2020-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_base', models.CharField(max_length=70)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=12)),
            ],
        ),
    ]
