# Generated by Django 3.0.3 on 2020-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea_base', '0002_auto_20200427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineabase',
            name='estado',
            field=models.CharField(choices=[('Bloqueado', 'Bloqueado'), ('Desbloqueado', 'Desbloqueado')], max_length=12),
        ),
    ]
