# Generated by Django 3.0.3 on 2020-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('prioridad', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('id_tarea_padre', models.IntegerField(null=True)),
            ],
        ),
    ]
