# Generated by Django 3.0.3 on 2020-04-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja'), ('Normal', 'Normal')], max_length=10)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], max_length=15)),
                ('id_tarea_padre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
    ]
