# Generated by Django 3.0.3 on 2020-03-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], max_length=15),
        ),
    ]
