# Generated by Django 3.0.3 on 2020-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_auto_20200319_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja'), ('Normal', 'Normal')], max_length=10),
        ),
    ]
