# Generated by Django 3.0.3 on 2020-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('permiso', models.CharField(choices=[('administracion', 'Administracion'), ('desarrollo', 'Desarrollo'), ('configuracion', 'Configuracion')], max_length=14)),
            ],
        ),
    ]
